let g:pymode_lint = 1
let g:pymode_motion = 1
let g:pymode_rope = 1
let g:pymode_rope_completion = 0
let g:pymode_rop_complete_on_dot = 0
let g:pymode_doc = 1
let g:pymode_indent = 1
let g:pymode_doc_bind = "K"
"let g:pymode_lint_ignore = "E501"
let g:pymode_lint_ignore = "W0401"
let g:pymode_options_max_line_length = 120
"let g:pymode_lint_checker = "pep8,pyflakes,pylint"
let g:pymode_lint_checker = ['pep8', 'pylint']
let g:pymode_folding = 0
let g:pymode_options_colorcolumn = 0
